#!/usr/bin/env node

const fs = require('fs');
const parser = require('shift-parser');
const codegen = require('shift-codegen').default;

if (process.argv.length != 3) {
    console.log('es6-minify.js inputfile');
    process.exit(-1);
}

const inputfile = process.argv[2];
const source = fs.readFileSync(inputfile, 'utf-8');
const ast = parser.parseScript(source);
const output = codegen(ast);
console.log(output);
