#!/bin/bash

export NODE_ENV=development
export WEBDESIGNIO_CLUSTER_URL=
trap 'kill $(jobs -p) 2>/dev/null' EXIT
[[ -z $PORT ]] && mongod --dbpath data/ >mongod.log &
watch-run -i -p 'src/components/**,!src/components/index.js' \
  scripts/create_component_index > src/components/index.js &
watchify \
  -s CMS \
  -t [ babelify --presets [ react es2015 ] ] \
  -t envify \
  -o client.js \
  src/client.js \
  -v &
node-inspector &
node-dev --debug server.js
