#!/bin/bash

export NODE_ENV=development
export WEBDESIGNIO_CLUSTER_URL=
trap 'kill $(jobs -p) 2>/dev/null' EXIT
watch-run -i -p 'src/components/**,!src/components/index.js' \
  node scripts/create_component_index > src/components/index.js &
watchify \
  -s CMS \
  -t [ babelify --presets [ react es2015 ] ] \
  -t envify \
  -o static/client.js \
  src/client.js \
  -v &
node-dev server.js
